### ISSUE TITLE
Add a toggable workaround for `PlayerUse` hook of Playable Piano 

### ISSUE THREAD

**Issue by Guthen** [Guthen/guthscpbase#4]
## Description
Since the original [Playable Piano](https://steamcommunity.com/sharedfiles/filedetails/?id=104548572) is conflicting with [guthscpkeycard](https://github.com/Guthen/guthscpkeycard) and is not maintained by his author since a decade, I should make a workaround script to fix it myself.

It will be toggable in the `guthscpbase` menu but will probably need server restart to apply properly (specially to disable a workaround).

I also want to make a simple system to eventually add more workarounds in the future (e.g. CPTBase)

## Todo
+ [x] Workaround system
+ [x] Implement workaround for Playable Piano
+ [x] Implement workaround for CPTBase 
+ [x] Add its own Configuration page
+ [x] Save & Load
